Рабочая тетрадь 2

### 1.3.1 Задание
Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и
единицами.

In [1]:
import numpy as np

Z = np.zeros((8,8), dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### 1.3.3 Задание
Создать массив 3x3x3 со случайными значениями.


In [2]:
import numpy as np

Z = np.random.random((3,3,3))
print(Z)

[[[0.60400243 0.47596081 0.8162886 ]
  [0.39086013 0.95888869 0.69093229]
  [0.03903681 0.89691714 0.68727668]]

 [[0.1198399  0.25195138 0.68457007]
  [0.05259778 0.92302342 0.27649583]
  [0.7808555  0.60882389 0.0207771 ]]

 [[0.99573408 0.81809215 0.57760953]
  [0.30684103 0.26832336 0.20078202]
  [0.88957396 0.62760511 0.90871266]]]


### 1.3.4 Задание
Создать матрицу с 0 внутри, и 1 на границах.

In [3]:
import numpy as np

Z = np.ones((10,10))
Z[1:-1,1:-1] = 0

print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


### 1.3.5 Задание
Создайте массив и отсортируйте его по убыванию.

In [4]:
import numpy as np

Z = np.random.random((5))
print(np.sort(Z)[::-1])

[0.92286833 0.58360045 0.3972245  0.13826543 0.03375583]


### 1.3.6 Задание
Создайте матрицу, выведите ее форму, размер и размерность.

In [5]:
import numpy as np

Z = np.random.random((3,3,3))

print(Z)

print("Форма матрицы:", Z.shape)

print("Размер матрицы:", Z.size)

print("Размерность матрицы:", Z.ndim)


[[[0.79286905 0.56179798 0.95786737]
  [0.42670286 0.76229756 0.01947861]
  [0.7835772  0.53595331 0.16157201]]

 [[0.40712914 0.20994626 0.11383339]
  [0.17989389 0.31770798 0.71009391]
  [0.63776861 0.65824884 0.14712749]]

 [[0.66680265 0.62103438 0.24520209]
  [0.88572639 0.34167073 0.9744885 ]
  [0.99780897 0.06393287 0.16870566]]]
Форма матрицы: (3, 3, 3)
Размер матрицы: 27
Размерность матрицы: 3


### 2.3.1 Задание
Найдите евклидово расстояние между двумя Series (точками) a и b, не
используя встроенную формулу.

In [6]:
import pandas as pd
import numpy as np

a = pd.Series([1, 2])
b = pd.Series([3, 4])

euclidean_distance = np.sqrt(((a - b) ** 2).sum())

print("Евклидово расстояние между точками a и b:", euclidean_distance)

Евклидово расстояние между точками a и b: 2.8284271247461903


### 2.3.2 Задание
Найдите в Интернете ссылку на любой csv файл и сформируйте из него
фрейм данных (например, коллекцию фреймов данных можно найти
здесь: https://github.com/akmand/datasets).

In [7]:
import pandas as pd

url = './airlines.csv'
dataframe = pd.read_csv(url)
dataframe.head(3)

Airline  Flight AirportFrom AirportTo  DayOfWeek  Time  Length  Delay
0      CO     269         SFO       IAH          3    15     205      1
1      US    1558         PHX       CLT          3    15     222      1
2      AA    2400         LAX       DFW          3    20     165      1

### 2.3.3 Задание
Проделайте с получившемся из предыдущего задания фреймом данных
те же действия, что и в примерах 2.2.5-2.2.7.


In [8]:
import pandas as pd

url = './airlines.csv'
dataframe = pd.read_csv(url)

dataframe.head(2)
dataframe.tail(3)
dataframe.shape
dataframe.describe()

dataframe.iloc[1:4]

dataframe[dataframe['Airline'] == 'US']

Airline  Flight AirportFrom AirportTo  DayOfWeek  Time  Length  Delay
1           US    1558         PHX       CLT          3    15     222      1
15          US     498         DEN       CLT          3    55     179      0
24          US     122         ANC       PHX          3   113     327      1
31          US    1011         EWR       CLT          3   300     111      0
32          US    1983         BOS       CLT          3   300     135      0
...        ...     ...         ...       ...        ...   ...     ...    ...
539353      US      31         OGG       PHX          5  1410     344      0
539365      US     119         KOA       PHX          5  1425     349      1
539366      US     258         PHX       PHL          5  1425     254      0
539369      US     125         HNL       PHX          5  1430     362      0
539382      US    1442         LAX       PHL          5  1439     301      1

[34500 rows x 8 columns]

### 3.3.2 Задание
Загрузить фрейм данных по ссылке:
https://raw.githubusercontent.com/akmand/datasets/master/iris.csv.
Необходимо выполнить нормализацию первого числового признака
(sepal_length_cm) с использованием минимаксного преобразования, а
второго (sepal_width_cm) с задействованием z-масштабирования.

In [9]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler, StandardScaler

url = './iris.csv'
df = pd.read_csv(url)

print("Исходные данные:")
print(df.head())

min_max_scaler = MinMaxScaler()
df['sepal_length_cm'] = min_max_scaler.fit_transform(df[['sepal_length_cm']])

z_scaler = StandardScaler()
df['sepal_width_cm'] = z_scaler.fit_transform(df[['sepal_width_cm']])

print("\nДанные после нормализации:")
print(df.head())

Исходные данные:
   sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm species
0              5.1             3.5              1.4             0.2  setosa
1              4.9             3.0              1.4             0.2  setosa
2              4.7             3.2              1.3             0.2  setosa
3              4.6             3.1              1.5             0.2  setosa
4              5.0             3.6              1.4             0.2  setosa

Данные после нормализации:
   sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm species
0         0.222222        1.032057              1.4             0.2  setosa
1         0.166667       -0.124958              1.4             0.2  setosa
2         0.111111        0.337848              1.3             0.2  setosa
3         0.083333        0.106445              1.5             0.2  setosa
4         0.194444        1.263460              1.4             0.2  setosa
